import { StyleSheet } from "react-native";
import { FONTS } from "@/constants/Theme";

export default StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingTop: 100,
    },
    section: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 11,
        fontWeight: "bold",
        fontFamily: FONTS.quicksand,
        letterSpacing: 1.2,
        marginBottom: 8,
        marginLeft: 4,
        color: "#6B7280",
    },
    card: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingHorizontal: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
        borderWidth: 1,
        borderColor: "rgba(240, 240, 240, 0.8)",
    },
    cardTag: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
        borderWidth: 1,
        borderColor: "rgba(240, 240, 240, 0.8)",
    },
    textArea: {
        fontSize: 14,
        fontFamily: FONTS.quicksand,
        lineHeight: 20,
        minHeight: 25,
    },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    tagCapsule: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    tagText: {
        fontSize: 13,
        fontWeight: "600",
        fontFamily: FONTS.quicksand,
    },
    addMoreButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#8C7A6B",
        borderStyle: "dashed",
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
    addMoreText: {
        fontSize: 13,
        fontWeight: "600",
        fontFamily: FONTS.quicksand,
        color: "#8C7A6B",
    },
    inputWrapper: {
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#8C7A6B",
        backgroundColor: "#FFF",
        justifyContent: "center",
        alignItems: "center",
        minWidth: 80,
    },
    customInput: {
        fontSize: 13,
        fontWeight: "600",
        fontFamily: FONTS.quicksand,
        color: "#8C7A6B",
        padding: 0,
        textAlign: "center",
    },
    buttonContainer: {
        paddingHorizontal: 16,
        marginTop: 12,
        marginBottom: 32,
    },
    saveButton: {
        borderRadius: 12,
        height: 48,
    },
});
