import { StyleSheet } from "react-native";
import { FONTS } from "@/constants/Theme";

export default StyleSheet.create({
    container: {
        marginBottom: 16,
    },
    sectionHeaderTitle: {
        fontSize: 11,
        fontWeight: "bold",
        fontFamily: FONTS.quicksand,
        letterSpacing: 1.2,
        marginBottom: 8,
        marginLeft: 4,
        color: "#6B7280",
    },
    card: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
        borderWidth: 1,
        borderColor: "rgba(240, 240, 240, 0.8)",
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 14,
    },
    rowLabel: {
        fontSize: 14,
        fontWeight: "600",
        fontFamily: FONTS.quicksand,
    },
    timeValueBox: {
        backgroundColor: "rgba(242, 236, 228, 0.4)",
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 16,
        minWidth: 70,
        alignItems: "center",
    },
    timeValueText: {
        fontSize: 14,
        fontWeight: "700",
        fontFamily: FONTS.quicksand,
    },
    divider: {
        height: 1,
        backgroundColor: "rgba(243, 244, 246, 0.8)",
    },
    pickerWrapper: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        height: 130,
        overflow: "hidden",
        position: "relative",
        marginVertical: 8,
        backgroundColor: "#FCFAF7",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(240, 240, 240, 0.8)",
    },
    pickerHighlightBar: {
        position: "absolute",
        left: 0,
        right: 0,
        height: 36,
        backgroundColor: "rgba(242, 236, 228, 0.3)",
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: "rgba(233, 97, 0, 0.15)",
        zIndex: 0,
    },
    pickerSeparator: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#e96100",
        marginHorizontal: 16,
        zIndex: 1,
    },
});
