import { StyleSheet } from "react-native";
import { COMMON_COLORS, FONTS } from "@/constants/Theme";

export default StyleSheet.create({
  scrollContainer: {
    paddingBottom: 40,
  },
  avatarWrapper: {
        position: "relative",
        zIndex: 2,
        width: 160,
        height: 160,
        alignItems: "center",
        justifyContent: "center",
    },
    avatarContainer: {
        width: 150,
        height: 150,
        borderRadius: 75,
        borderWidth: 6,
        overflow: "hidden",
        backgroundColor: "#fdeede",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: COMMON_COLORS.secondary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 10,
    },
    avatarImage: {
        width: "100%",
        height: "100%",
        borderRadius: 75,
    },
    headerTextWrapper: {
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 20,
    },
    headerText: {
      fontSize: 14,
      color: "#656972",
    },
    profileSection: {
      alignItems: "center",
      marginVertical: 20,
    },
    imageWrapper: {
      position: "relative",
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: "#E5E5E5",
    },
    editPhotoBtn: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: "#FF7F50",
      padding: 8,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: "#FFF",
    },
    editPhotoIcon: {
      color: "#FFF",
      fontSize: 14,
    },
    card: {
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#f1f5f9",
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.02,
      shadowRadius: 8,
      elevation: 2,
    },
    label: {
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 12,
      color: "#64748b",
      fontFamily: `${FONTS.quicksand}-Bold`,
    },
    inputContainerRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    inputIcon: {
      marginRight: 12,
    },
    bottomBorderInput: {
      flex: 1,
      borderBottomWidth: 1,
      borderBottomColor: "#cbd5e1",
      fontSize: 16,
      fontWeight: "700",
      color: "#0f172a",
      paddingVertical: 6,
      paddingHorizontal: 0,
      fontFamily: `${FONTS.quicksand}-Bold`,
    },
    inputGroup: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
      borderRadius: 10,
      paddingHorizontal: 15,
      borderWidth: 1,
      borderColor: "#DDD",
    },
    icon: {
      width: 20,
      height: 20,
      marginRight: 10,
      resizeMode: "contain",
    },
    input: {
      flex: 1,
      height: 50,
      color: "#333",
    },
    textArea: {
      height: 100,
      paddingTop: 15,
      backgroundColor: "#F9F9F9",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#DDD",
      paddingHorizontal: 15,
    },
    errorText: {
      color: "red",
      fontSize: 12,
      marginTop: 4,
    },
    saveButton: {
      marginHorizontal: 20,
      marginTop: 10,
    },
    button: {
      paddingVertical: 15,
    },
    menuContainer: {
        marginTop: 10,
        paddingBottom: 40,
    },
    tableCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        // marginHorizontal: 16,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "rgba(238, 218, 203, 0.8)",
    },
    tableRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 18,
        paddingHorizontal: 18,
    },
    tableDivider: {
        height: 1,
        backgroundColor: "rgba(238, 218, 203, 0.5)",
    },
    labelContainer: {
        width: 120,
    },
    rowLabel: {
        fontSize: 15,
        fontWeight: "600",
        color: "#334155",
        fontFamily: `${FONTS.quicksand}-Bold`,
    },
    valueContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
    },
    rowValue: {
        fontSize: 15,
        color: "#475569",
        fontFamily: FONTS.quicksand,
    },
    arrowContainer: {
        width: 20,
        alignItems: "flex-end",
    },
    arrowIcon: {
        opacity: 0.5,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 40,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#0f172a",
        fontFamily: `${FONTS.quicksand}-Bold`,
    },
    modalInput: {
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        color: "#0f172a",
        fontFamily: FONTS.quicksand,
        marginBottom: 20,
    },
    modalButtonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 12,
    },
    modalCancelBtn: {
        flex: 1,
        backgroundColor: "#f1f5f9",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    modalSaveBtn: {
        flex: 1,
        backgroundColor: COMMON_COLORS.secondary,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
    },
    modalCancelText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#475569",
        fontFamily: `${FONTS.quicksand}-Bold`,
    },
    modalSaveText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#FFFFFF",
        fontFamily: `${FONTS.quicksand}-Bold`,
    },
});