import { StyleSheet } from "react-native";
import { FONTS } from "@/constants/Theme";

export default StyleSheet.create({
    actionButton: {
        flex: 1,
        height: 40,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        borderWidth: 1,
    },
    buttonText: {
        fontFamily: `${FONTS.montserrat}-Bold`,
        fontSize: 12,
        fontWeight: "700",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 24, 70, 0.6)",
        justifyContent: "center",
        alignItems: "center",
        padding: 24,
    },
    modalContent: {
        width: "100%",
        borderRadius: 24,
        padding: 24,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 15,
        elevation: 10,
    },
    contentContainer: {
        width: "100%",
        alignItems: "center",
    },
    modalTitle: {
        fontFamily: `${FONTS.montserrat}-Bold`,
        fontSize: 18,
        fontWeight: "800",
        marginBottom: 8,
        textAlign: "center",
    },
    modalSubtitle: {
        fontFamily: `${FONTS.quicksand}-Medium`,
        fontSize: 13,
        textAlign: "center",
        marginBottom: 20,
        lineHeight: 18,
        paddingHorizontal: 12,
    },
    qrContainer: {
        padding: 16,
        borderRadius: 20,
        borderWidth: 1,
        marginBottom: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    scannerWrapper: {
        width: 250,
        height: 250,
        borderRadius: 20,
        overflow: "hidden",
        marginBottom: 20,
        position: "relative",
        backgroundColor: "#000",
    },
    permissionPlaceholder: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    permissionText: {
        fontFamily: `${FONTS.quicksand}-Medium`,
        fontSize: 12,
        marginTop: 8,
    },
    overlayFrame: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.4)",
        justifyContent: "center",
        alignItems: "center",
    },
    scannerBox: {
        width: 180,
        height: 180,
        position: "relative",
        backgroundColor: "transparent",
    },
    corner: {
        position: "absolute",
        width: 24,
        height: 24,
        borderWidth: 4,
    },
    topLeft: {
        top: 0,
        left: 0,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderTopLeftRadius: 8,
    },
    topRight: {
        top: 0,
        right: 0,
        borderLeftWidth: 0,
        borderBottomWidth: 0,
        borderTopRightRadius: 8,
    },
    bottomLeft: {
        bottom: 0,
        left: 0,
        borderRightWidth: 0,
        borderTopWidth: 0,
        borderBottomLeftRadius: 8,
    },
    bottomRight: {
        bottom: 0,
        right: 0,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderBottomRightRadius: 8,
    },
    closeButton: {
        width: "100%",
        height: 48,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
    },
    closeButtonText: {
        fontFamily: `${FONTS.montserrat}-Bold`,
        fontSize: 14,
        fontWeight: "700",
        color: "#ffffff",
    },
});
