name: Deploy Firebase Functions

on:
  push:
    branches:
      - function

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.22.2'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        run: npm run firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
